---
- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0640'
  no_log: true
  with_items: '{{ restic_repos }}'
  register: _cronfiles

- name: Deploy helper commands
  template:
    src: 'restic.helper.j2'
    dest: "{{ _restic_install_path }}/restic-{{ item.name }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0750'
  no_log: true
  with_items: '{{ restic_repos }}'

- name: Whitelist restic to run certain commands with sudo
  template:
    src: 'restic.sudoers.j2'
    dest: "/etc/sudoers.d/restic-sudoers"
    owner: root
    group: root
    mode: '0440'
    validate: "visudo -cf %s"
  when: restic_user != 'root'

- name: Initialize restic repositories
  command: "{{ _restic_install_path }}/restic-{{ item.name }} init"
  ignore_errors: true
  no_log: true
  with_items: "{{ restic_repos }}"
  when:
    - _cronfiles is changed
    - restic_initialize_repos
