---
- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0640'
  no_log: true

- name: Ensure runrestic backup conf files exist
  template:
    src: backup.toml.j2
    dest: "{{ restic_conf_dir }}/{{ item.name }}.toml"
  no_log: true

- name: Check if repo is already initialized
  command: restic -r {{ item.urls[0] | trim | quote }} snapshots
  environment:
    RESTIC_PASSWORD: "{{ item.password | trim }}"
  changed_when: false
  failed_when: false
  check_mode: false
  no_log: true
  register: repo

- name: Initialize restic repositories
  command: "runrestic -c {{ restic_conf_dir }}/{{ item.name }}.toml init"
  ignore_errors: true
  no_log: true
  when:
    - repo.rc != 0
    - restic_initialize_repos
