---
- name: Ensure run restic is installed
  pip:
    name: runrestic
    version: "{{ runrestic_version }}"
    executable: pip3

- name: Ensure restic conf path exists
  file:
    path: /etc/restic
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: Ensure pormetheus metrics dir exist
  file:
    path: "{{ restic_prometheus_dir }}"
    state: directory
  when: restic_prometheus_dir | bool
